services:
  web:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .local_env
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:15"
    expose:
      - 5432
    env_file:
      - .local_env
    environment:
      - POSTGRES_DB=lists
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: